// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    int32_t capacity;
    int32_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef int32_t (*ForeignCallback)(uint64_t, int32_t, RustBuffer, RustBuffer *_Nonnull);

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H

void ffi_aethers_afd5_Wallet_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull aethers_afd5_Wallet_new(
      RustBuffer password,uint64_t chain_id,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_Wallet_request_accounts(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_Wallet_encrypt_json(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_Wallet_recover_phrase(
      void*_Nonnull ptr,RustBuffer password,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_Wallet_sign_typed_message(
      void*_Nonnull ptr,RustBuffer message,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_Wallet_send_transaction(
      void*_Nonnull ptr,void*_Nonnull provider,RustBuffer payload,
    RustCallStatus *_Nonnull out_status
    );
void ffi_aethers_afd5_ChainProvider_object_free(
      void*_Nonnull ptr,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_ec_recover(
      RustBuffer signature,RustBuffer message,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull aethers_afd5_decrypt_json_bytes(
      RustBuffer encrypted,RustBuffer password,uint64_t chain_id,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull aethers_afd5_decrypt_json(
      RustBuffer encrypted,RustBuffer password,uint64_t chain_id,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull aethers_afd5_from_mnemonic(
      RustBuffer mnemonic,RustBuffer password,uint64_t chain_id,
    RustCallStatus *_Nonnull out_status
    );
void*_Nonnull aethers_afd5_provider_from_url(
      RustBuffer url,
    RustCallStatus *_Nonnull out_status
    );
void aethers_afd5_init_logger(
      
    RustCallStatus *_Nonnull out_status
    );
RustBuffer aethers_afd5_impl_version(
      
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_aethers_afd5_rustbuffer_alloc(
      int32_t size,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_aethers_afd5_rustbuffer_from_bytes(
      ForeignBytes bytes,
    RustCallStatus *_Nonnull out_status
    );
void ffi_aethers_afd5_rustbuffer_free(
      RustBuffer buf,
    RustCallStatus *_Nonnull out_status
    );
RustBuffer ffi_aethers_afd5_rustbuffer_reserve(
      RustBuffer buf,int32_t additional,
    RustCallStatus *_Nonnull out_status
    );
